services:
  - type: web
    name: cricheroes
    env: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --workers 1 --threads 2 --timeout 60
